# shopify.app.toml
client_id = "7124aea5b2847e4a95178bb8f0d8c6ae"
name = "AR Viewer"
application_url = "https://ecommerce-web-ar-server.vercel.app"
embedded = false

[access_scopes]
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://ecommerce-web-ar-server.vercel.app/api/shopify/callback"
]

[webhooks]
api_version = "2025-01"

[pos]
embedded = false